version: "3.3"

services:
  db:
    container_name: db
    image: postgres:16.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5433:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  nextapp:
    container_name: nextapp
    image: pierremarcade/nextapp:1.0.0
    build:
      context: ./frontend
      dockerfile: next.dockerfile
    ports:
      - 3000:3000
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    depends_on:
      - barkeel
  barkeel:
    container_name: barkeel
    image: pierremarcade/barkeel:1.0.0
    build:
      context: ./backend
      dockerfile: rust.dockerfile
      args:
        DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
    ports:
      - '8080:8080'
    depends_on:
      - db


volumes:
  pgdata: {}